language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26
    
    # Override the install and test so that we don't run integration tests
install:
  - ./gradlew assemble
